/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Deepak
 */


public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */


    int allmyvalues[] = new int[6];
    int allmycolors[] = new int[6];
    Deck d=new Deck();
    Deck d1=new Deck();
    Hand h1= new Hand();
    Hand h2= new Hand();
    Card f1,f2,f3,f4,f5,f6;
    int coins=0;
    int bet=0;
    int coin=0;
    int bets=0;
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 30, 255));
        jButton5.setText("SEE CARDS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 130, 40));

        jButton4.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 24)); // NOI18N
        jButton4.setForeground(java.awt.Color.red);
        jButton4.setText("SHOW");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 100, 40));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 130, 80, 140));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 80, 150));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 80, 150));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 90, 150));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 90, 150));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 100, 150));

        jLabel3.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jLabel3.setText("PLAYER 2");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, -1, 50));

        jLabel1.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jLabel1.setText("PLAYER 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 150, 50));

        jButton3.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setText("SEE CARDS\n");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 450, 130, 40));

        jButton2.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 24)); // NOI18N
        jButton2.setForeground(java.awt.Color.yellow);
        jButton2.setText("DEAL CARDS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, -1, -1));

        jButton1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 24)); // NOI18N
        jButton1.setForeground(java.awt.Color.red);
        jButton1.setText("SHOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, -1, -1));

        jButton6.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jButton6.setText("+");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));

        jButton7.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jButton7.setText("-");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabel11.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel11.setText("0");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        jButton8.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 18)); // NOI18N
        jButton8.setText("BET COINS\n");
        jButton8.setActionCommand("BET COINS");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 120, -1));

        jLabel10.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("BET AMOUNT");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 180, 30));

        jLabel12.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 530, 30));

        jButton9.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jButton9.setText("-");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, -1, -1));

        jButton10.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jButton10.setText("+");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, -1, -1));

        jLabel13.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        jLabel13.setText("0");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, -1, -1));

        jLabel14.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 18)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("BET AMOUNT");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 180, 30));

        jButton11.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 18)); // NOI18N
        jButton11.setText("BET COINS");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, -1, -1));

        jButton12.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 1, 18)); // NOI18N
        jButton12.setText("EXIT");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 520, 80, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Gui_bg.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 1060, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    
        
        d.shuffle();
        
        f1= d.player1.get(0);
        f2= d.player1.get(1);
        f3= d.player1.get(2);
         
       
        
        System.out.println(f1.getSuit());
        allmyvalues[0] = (f1.getValue()+2);
        System.out.println(allmyvalues[0]);
        allmyvalues[1] = (f2.getValue()+2);
        allmyvalues[2] = (f3.getValue()+2);
        
        allmycolors[0] = f1.getSuit();
        allmycolors[1] = f2.getSuit();
        allmycolors[2] = f3.getSuit();
        
        h1.addcard(f1);
        h1.addcard(f2);
        h1.addcard(f3);
        
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+f1.getImg())));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+f2.getImg())));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+f3.getImg())));
        
         
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1fv.png")));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1fv.png")));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1fv.png")));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1fv.png")));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1fv.png")));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1fv.png"))); 
        
        jLabel12.setText("");
        jLabel10.setText("BET AMOUNT");
        jLabel14.setText("BET AMOUNT");
        jLabel11.setText("0");
        jLabel13.setText("0");
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
        d.shuffle();
        f4= d.player2.get(3);
        f5= d.player2.get(4);
        f6= d.player2.get(5);
        
        h2.addcard(f4);
        h2.addcard(f5);
        h2.addcard(f6);
        
        allmyvalues[3] = (f4.getValue()+2);
        allmyvalues[4] = (f5.getValue()+2);
        allmyvalues[5] = (f6.getValue()+2);
        
        allmycolors[3] = f4.getSuit();
        allmycolors[4] = f5.getSuit();
        allmycolors[5] = f6.getSuit();
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+f4.getImg())));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+f5.getImg())));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/"+f6.getImg()))); 
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(coins>0)
        {
        coins=coins-500;
        jLabel11.setText(""+coins);
        }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        coins=coins+500;
        jLabel11.setText(""+coins);
                
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        bet=bet+coins;
        jLabel10.setText("BET AMOUNT : "+bet);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        afterShow(allmyvalues,allmycolors);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        afterShow(allmyvalues,allmycolors);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(coin>0)
        {
        coin=coin-500;
        jLabel13.setText(""+coin);
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         coin=coin+500;
        jLabel13.setText(""+coin);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        bets=bets+coin;
        jLabel14.setText("BET AMOUNT : "+bets);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton12ActionPerformed

    public void afterShow(int[] values, int[] colors){
        //three of a kind
        if((values[3]==values[4]) && (values[3] ==values[5]) && (values[0]==values[1]) && (values[0]==values[2])){
            if(values[3]>values[0])
               jLabel12.setText("Player 2 is winner and won "+bet*2+" coins");
            jLabel12.setText("Player 1 is winner and won "+bet*2+" coins");
        }
        //Sequence
        if((values[4]==values[3]+1) && (values[5] ==values[4]+1) && (values[1]==values[0]+1) && (values[2]==values[1]+1)){
            if(values[3]>values[0])
               jLabel12.setText("Player 2 is winner and won "+bet*2+" coins");
            jLabel12.setText("Player 1 is winner and won "+bet*2+" coins");
        }
        //color
        if((colors[3]==colors[4]) && (colors[3] ==colors[5]) && (colors[0]==colors[1]) && (colors[0]==colors[2])){
            if(colors[3]>values[0])
               jLabel12.setText("Player 1 is winner and won "+bet*2+" coins");
            jLabel12.setText("Player 2 is winner and won "+bet*2+" coins");
        }
        
        //Two of a kind 
        if((values[3]==values[4]) || (values[3] ==values[5]) || (values[4] ==values[5]) && ( (values[0]==values[1]) || (values[0]==values[2]) ||  (values[1]==values[2]) || (values[0]==values[2]))){
            if(values[3]>values[0])
               jLabel12.setText("Player 2 is winner and won "+bet*2+" coins");
            jLabel12.setText("Player 1 is winner and won "+bet*2+" coins");
        }    
       int cmp1=0,cmp2=0;     
       if(values[3]==values[4]) 
         {
                cmp1 = values[3];
         }
        
         if(values[4]==values[5]) 
         {
           cmp1 = values[4];
         }
         
         if(values[3]==values[5]) 
         {
            cmp1 = values[3];
         }
         
       if(values[0]==values[1]) 
         {
                 cmp2 = values[0];
         }
        
         if(values[1]==values[2]) 
         {
            cmp2 = values[1];
         }
         
          
         
         if(values[0]==values[2]) 
         {
            cmp2 = values[0];
         }
         
         if(cmp1>cmp2){
           jLabel12.setText("Player 2 is winner and won "+bet*2+" coins");  
         }
         else{
            jLabel12.setText("Player 1 is winner and won "+bet*2+" coins");    
         }  
        
         //none of the above cards will perform this operation
         
         if((values[0]+values[1]+values[2])>((values[3])+values[4]+values[5]))
             jLabel12.setText("Player 1 is winner and won "+bet*2+" coins");
         else
             jLabel12.setText("Player 2 is winner and won "+bet*2+" coins");
         
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
